name: Daily Dodgers Win Check
on:
  schedule:
    - cron: '0 8 * * *'  # 12AM PST = 8AM UTC
  workflow_dispatch:  # allows manual triggering

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Dodgers win check
        run: python main.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          
      - name: Upload schedule file as artifact (for debugging)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: schedule-data
          path: home_games_schedule.json 