name: Test Dodgers Win Check
on:
  workflow_dispatch:
    inputs:
      test_date:
        description: 'Test date (YYYY-MM-DD)'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run test with specific date
        run: |
          echo "Testing with date: ${{ github.event.inputs.test_date }}"
          python -c "
          import asyncio
          import sys
          sys.path.append('.')
          from main import main
          asyncio.run(main(test_date='${{ github.event.inputs.test_date }}'))
          "
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          
      - name: Upload schedule file as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-schedule-data
          path: home_games_schedule.json 